(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const K={equipment:'ravitoai-equipment-v1',hydration:'ravitoai-hydration-v1'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function injectStyles(){if($('#build21-styles'))return;document.head.insertAdjacentHTML('beforeend',`<style id="build21-styles">
#profile-form input:not(:placeholder-shown),#profile-form select{color:#0f172a;font-weight:750;opacity:1}#profile-form input::placeholder{color:#a8b1c0;font-weight:500}body.dark #profile-form input:not(:placeholder-shown),body.dark #profile-form select{color:#f8fafc}input[readonly]{opacity:1}.equipment-item.compact-item{position:relative;grid-template-columns:1fr auto;padding:15px 58px 15px 15px}.trash-icon{position:absolute;right:12px;top:50%;transform:translateY(-50%);width:38px;height:38px;border:0;border-radius:50%;background:rgba(239,68,68,.10);color:#dc2626;font-size:1.05rem;display:grid;place-items:center}.trash-icon:active{transform:translateY(-49%)}.equipment-item .item-meta{display:grid;gap:3px}.equipment-item .item-meta span{display:block}.equipment-item .shoe-km{font-weight:800;color:var(--accent-dark)}
</style>`)}
function cleanEquipment(){const raw=read(K.equipment,[]),seen=new Set(),clean=[];raw.forEach(x=>{const brand=String(x.brand||'').trim(),model=String(x.model||'').trim();if(!brand||!model)return;const key=`${x.type||'other'}|${brand.toLowerCase()}|${model.toLowerCase()}`;if(seen.has(key))return;seen.add(key);clean.push({...x,brand,model,km:Number(x.km)||0,use:x.use||((x.type==='shoe')?'Entraînement quotidien':'Équipement')})});write(K.equipment,clean);return clean}
function cleanHydration(){const raw=read(K.hydration,[]),map=new Map();raw.forEach(x=>{const type=x.type||'flask',capacity=Number(x.capacity)||0,quantity=Math.max(1,Number(x.quantity)||1);if(!capacity)return;const key=`${type}|${capacity}`;const old=map.get(key);map.set(key,old?{...old,quantity:old.quantity+quantity}:{type,capacity,quantity})});const clean=[...map.values()];write(K.hydration,clean);return clean}
function renderEquipment(){const list=cleanEquipment(),box=$('#equipment-list');if($('#equipment-count'))$('#equipment-count').textContent=`${list.length} équipement${list.length>1?'s':''}`;if(!box)return;box.innerHTML=list.length?list.map((x,i)=>`<article class="equipment-item compact-item"><div class="item-meta"><strong>${esc(x.brand)} ${esc(x.model)}</strong><span>${x.type==='shoe'?'🏃 Route':x.type==='vest'?'🎒 Gilet / sac':x.type==='belt'?'🎽 Ceinture':'Équipement'}</span>${x.type==='shoe'?`<span class="shoe-km">📏 ${Number(x.km)||0} km · ⭐ ${esc(x.use)}</span>`:''}</div><button class="trash-icon" data-del-equipment21="${i}" type="button" aria-label="Supprimer ${esc(x.brand)} ${esc(x.model)}">🗑️</button></article>`).join(''):'<p class="empty">Aucun équipement enregistré.</p>';$$('[data-del-equipment21]').forEach(b=>b.onclick=()=>{const next=cleanEquipment();next.splice(Number(b.dataset.delEquipment21),1);write(K.equipment,next);renderEquipment()})}
function renderHydration(){const list=cleanHydration(),box=$('#hydration-list'),total=list.reduce((s,x)=>s+x.capacity*x.quantity,0);if($('#hydration-total'))$('#hydration-total').textContent=`${total} ml disponibles`;if(!box)return;box.innerHTML=list.length?list.map((x,i)=>`<article class="equipment-item compact-item"><div class="item-meta"><strong>${x.quantity} × ${x.capacity} ml</strong><span>${x.type==='flask'?'Flasque':x.type==='bladder'?"Poche d’hydratation":'Gourde'}</span></div><button class="trash-icon" data-del-hydration21="${i}" type="button" aria-label="Supprimer ce contenant">🗑️</button></article>`).join(''):'<p class="empty">Aucun contenant enregistré.</p>';$$('[data-del-hydration21]').forEach(b=>b.onclick=()=>{const next=cleanHydration();next.splice(Number(b.dataset.delHydration21),1);write(K.hydration,next);renderHydration()})}
function bindForms(){const ef=$('#equipment-form');if(ef)ef.onsubmit=e=>{e.preventDefault();const type=$('#equipment-type').value,brand=$('#equipment-brand').value.trim(),model=$('#equipment-model').value.trim();if(!brand||!model)return;const list=cleanEquipment(),exists=list.some(x=>x.type===type&&x.brand.toLowerCase()===brand.toLowerCase()&&x.model.toLowerCase()===model.toLowerCase());if(!exists)list.push({type,brand,model,km:0,use:type==='shoe'?'Entraînement quotidien':'Équipement'});write(K.equipment,list);ef.reset();renderEquipment()};const hf=$('#hydration-form');if(hf)hf.onsubmit=e=>{e.preventDefault();const type=$('#hydration-type').value,capacity=Number($('#hydration-capacity').value),quantity=Math.max(1,Number($('#hydration-quantity').value)||1),list=cleanHydration(),found=list.find(x=>x.type===type&&x.capacity===capacity);if(found)found.quantity+=quantity;else list.push({type,capacity,quantity});write(K.hydration,list);renderHydration()}}
function refreshProfileTone(){$$('#profile-form input').forEach(i=>i.classList.toggle('has-value',Boolean(String(i.value||'').trim())))}
function init(){injectStyles();const badge=$('.badge');if(badge)badge.textContent='BÊTA UTILISABLE · BUILD 21';bindForms();renderEquipment();renderHydration();refreshProfileTone();$('#profile-form')?.addEventListener('input',refreshProfileTone);$('#profile-form')?.addEventListener('submit',()=>setTimeout(refreshProfileTone,30));}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();