(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const K={projects:'ravitoai-projects-v1',equipment:'ravitoai-equipment-v1',hydration:'ravitoai-hydration-v1'};
function go(id){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$$('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===id));scrollTo({top:0,behavior:'smooth'});}
function initNav(){ $$('.quick-nav').forEach(b=>b.onclick=()=>go(b.dataset.go)); }
function renderProjects(){
 const list=read(K.projects,[]),box=$('#project-list'),count=$('#project-count');
 if(count)count.textContent=`${list.length} projet${list.length>1?'s':''}`;
 if(box)box.innerHTML=list.length?list.map((p,i)=>`<article class="project-item"><div><strong>${p.name}</strong><span>${p.discipline} · ${p.discipline==='hyrox'?'format Hyrox':`${p.distance} km`} · ${p.date||'date à définir'}${p.elevation&&p.discipline!=='hyrox'?` · D+ ${p.elevation} m`:''}</span></div><div class="product-actions"><button class="secondary" data-use-project="${i}" type="button">Créer le plan</button><button class="secondary" data-del-project="${i}" type="button">Supprimer</button></div></article>`).join(''):'<p class="empty">Aucun projet. Ajoute ta prochaine course ou ta sortie longue.</p>';
 const active=list[0],home=$('#home-project');
 if(home)home.innerHTML=active?`<strong>${active.name}</strong><span>${active.discipline==='hyrox'?'Hyrox':`${active.distance} km`} · ${active.date||'prochainement'}${active.time?` · objectif ${active.time}`:''}</span>`:'<strong>Aucun projet principal</strong><span>Ajoute ta prochaine compétition ou sortie longue.</span>';
 $$('[data-use-project]').forEach(b=>b.onclick=()=>{const p=list[+b.dataset.useProject];$('#race-name').value=p.name;$('#plan-discipline').value=p.discipline;const opt=[...$('#distance').options].find(o=>Number(o.value)===Number(p.distance));if(opt){$('#distance').value=opt.value;$('#custom-distance-wrap').classList.add('hidden')}else{$('#distance').value='custom';$('#custom-distance').value=p.distance||8;$('#custom-distance-wrap').classList.remove('hidden')}$('#plan-elevation').value=p.elevation||0;go('calculator')});
 $$('[data-del-project]').forEach(b=>b.onclick=()=>{list.splice(+b.dataset.delProject,1);write(K.projects,list);renderProjects()});
}
function initProjects(){renderProjects();window.addEventListener('ravitoai:projects-updated',renderProjects);}
function renderEquipment(){const list=read(K.equipment,[]),box=$('#equipment-list');if($('#equipment-count'))$('#equipment-count').textContent=`${list.length} équipement${list.length>1?'s':''}`;if(box)box.innerHTML=list.length?list.map((x,i)=>`<article class="equipment-item"><div><strong>${x.brand} ${x.model}</strong><span>${x.type==='shoe'?'Chaussure':x.type==='vest'?'Gilet / sac':x.type==='belt'?'Ceinture':'Autre'}</span></div><button class="secondary" data-del-equipment="${i}" type="button">Supprimer</button></article>`).join(''):'<p class="empty">Aucun équipement enregistré.</p>';$$('[data-del-equipment]').forEach(b=>b.onclick=()=>{list.splice(+b.dataset.delEquipment,1);write(K.equipment,list);renderEquipment()})}
function renderHydration(){const list=read(K.hydration,[]),box=$('#hydration-list'),total=list.reduce((s,x)=>s+x.capacity*x.quantity,0);if($('#hydration-total'))$('#hydration-total').textContent=`${total} ml disponibles`;if(box)box.innerHTML=list.length?list.map((x,i)=>`<article class="equipment-item"><div><strong>${x.quantity} × ${x.capacity} ml</strong><span>${x.type==='flask'?'Flasque':x.type==='bladder'?"Poche d’hydratation":'Gourde'}</span></div><button class="secondary" data-del-hydration="${i}" type="button">Supprimer</button></article>`).join(''):'<p class="empty">Aucun contenant enregistré.</p>';$$('[data-del-hydration]').forEach(b=>b.onclick=()=>{list.splice(+b.dataset.delHydration,1);write(K.hydration,list);renderHydration()})}
function initUniverse(){const ef=$('#equipment-form');if(ef)ef.onsubmit=e=>{e.preventDefault();const list=read(K.equipment,[]);list.push({type:$('#equipment-type').value,brand:$('#equipment-brand').value.trim(),model:$('#equipment-model').value.trim()});write(K.equipment,list);ef.reset();renderEquipment()};const hf=$('#hydration-form');if(hf)hf.onsubmit=e=>{e.preventDefault();const list=read(K.hydration,[]);list.push({type:$('#hydration-type').value,capacity:Number($('#hydration-capacity').value),quantity:Number($('#hydration-quantity').value)});write(K.hydration,list);renderHydration()};renderEquipment();renderHydration();}
function addLongRunPreset(){const intro=$('#calculator .intro-card');if(!intro||$('#long-run-preset'))return;intro.insertAdjacentHTML('afterend',`<section class="card"><p class="eyebrow">TEST BÊTA DU JOUR</p><h2>Préparer une sortie longue</h2><p class="summary">Préremplit un plan de 14 km en 1 h 15, à personnaliser avant génération.</p><button id="long-run-preset" class="primary" type="button">Utiliser le modèle sortie longue</button></section>`);$('#long-run-preset').onclick=()=>{$('#race-name').value='Sortie longue du jour';$('#distance').value='custom';$('#custom-distance-wrap').classList.remove('hidden');$('#custom-distance').value=14;$('#hours').value=1;$('#minutes').value=15;$('#temperature').focus();};}
function renderRaviCheck(){const p=window.RAVITO_LAST_PLAN,box=$('#ravicheck-content'),ctx=$('#ravicheck-context');if(!box||!p)return;const score=Math.max(0,Math.min(100,100-(p.stock?0:25)-(p.totalWater>1500?5:0)));if(ctx)ctx.textContent='Contrôle basé sur le dernier plan généré.';box.innerHTML=`<div class="score-card"><strong>${score}/100</strong><span>Score de préparation</span></div><div class="check-row"><div><strong>Glucides</strong><span>Cible</span></div><div><strong>${p.carbRate} g/h</strong><span>${p.totalCarbs} g au total</span></div></div><div class="check-row"><div><strong>Hydratation</strong><span>Cible</span></div><div><strong>${p.water} ml/h</strong><span>${p.totalWater} ml au total</span></div></div><div class="check-row"><div><strong>Stock</strong><span>Disponibilité</span></div><div><strong>${p.stock?'OK':'À compléter'}</strong><span>${p.stock?'Produits disponibles':'Ajoute les produits prévus'}</span></div></div>`;}
function init(){document.querySelector('.badge').textContent='BÊTA UTILISABLE · BUILD 20';initNav();initProjects();initUniverse();addLongRunPreset();$('#strategy-form')?.addEventListener('submit',()=>setTimeout(renderRaviCheck,120));}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();