(() => {
  const key='ravitoai-products-v1', profileKey='ravitoai-profile-v1';
  const $=s=>document.querySelector(s);
  const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const statusLabel={stock:'En stock',planned:'À acheter',none:'Non possédé'};
  let products=read(key,[]);
  function syncSelect(list=products){const usable=list.filter(p=>p.status==='stock');const source=usable.length?usable:products;const select=$('#product');if(!select)return;const previous=select.value;select.innerHTML=source.sort((a,b)=>Number(b.favorite)-Number(a.favorite)||a.brand.localeCompare(b.brand)).map(p=>`<option value="${p.id}">${p.brand} ${p.name} · ${p.carbs} g${p.status==='stock'?' · en stock':''}</option>`).join('');if(source.some(p=>p.id===previous))select.value=previous}
  function fillBrands(){const brand=$('#brand-filter');if(!brand)return;const old=brand.value;const brands=[...new Set(products.map(p=>p.brand))].sort((a,b)=>a.localeCompare(b));brand.innerHTML='<option value="all">Toutes les marques</option>'+brands.map(x=>`<option>${x}</option>`).join('');brand.value=brands.includes(old)?old:'all';fillModels()}
  function fillModels(){const brand=$('#brand-filter')?.value||'all', model=$('#model-filter');if(!model)return;const old=model.value;const models=products.filter(p=>brand==='all'||p.brand===brand).map(p=>p.name).sort((a,b)=>a.localeCompare(b));model.innerHTML='<option value="all">Tous les modèles</option>'+models.map(x=>`<option>${x}</option>`).join('');model.value=models.includes(old)?old:'all'}
  function suggestion(){const box=$('#inventory-suggestion');if(!box)return;const profile=read(profileKey,null), stock=products.filter(p=>p.status==='stock');if(!profile){box.innerHTML='<strong>Suggestion</strong><span>Complète ton profil pour obtenir une recommandation de produits.</span>';return}let preferred=stock.filter(p=>profile.digestion==='sensitive'?['gel','compote','drink'].includes(p.type):true);if(profile.carbMax>=75)preferred=preferred.filter(p=>p.carbs>=25);if(!preferred.length){box.innerHTML='<strong>Suggestion d’achat</strong><span>Aucun produit en stock ne correspond clairement à ton profil. Marque un gel de 20–30 g ou une boisson énergétique comme « prévu d’acheter ».</span>';return}const p=preferred.sort((a,b)=>Math.abs((profile.carbMax||60)/2-b.carbs)-Math.abs((profile.carbMax||60)/2-a.carbs))[0];box.innerHTML=`<strong>Suggestion profil</strong><span>${p.brand} ${p.name} : ${p.carbs} g par portion${profile.digestion==='sensitive'?' et format facile à fractionner':''}.</span>`}
  function render(){products=read(key,[]).map(p=>({...p,status:p.status||'none'}));const brand=$('#brand-filter')?.value||'all',model=$('#model-filter')?.value||'all',status=$('#stock-filter')?.value||'all',type=$('#product-filter')?.value||'all',q=($('#product-search')?.value||'').toLowerCase();const list=products.filter(p=>(brand==='all'||p.brand===brand)&&(model==='all'||p.name===model)&&(status==='all'||p.status===status)&&(type==='all'||p.type===type)&&`${p.brand} ${p.name}`.toLowerCase().includes(q));$('#product-count').textContent=`${products.filter(p=>p.status==='stock').length} en stock · ${products.filter(p=>p.status==='planned').length} prévus`;$('#product-list').innerHTML=list.length?list.map(p=>`<article class="product-item"><div><strong>${p.brand} · ${p.name}</strong><div class="product-meta">${p.carbs} g glucides · ${p.sodium} mg sodium${p.caffeine?` · ${p.caffeine} mg caféine`:''}</div></div><div class="inventory-actions"><select data-status="${p.id}"><option value="none" ${p.status==='none'?'selected':''}>Non possédé</option><option value="planned" ${p.status==='planned'?'selected':''}>Prévu d’acheter</option><option value="stock" ${p.status==='stock'?'selected':''}>En stock</option></select><button class="favorite" data-fav2="${p.id}" type="button">${p.favorite?'★':'☆'}</button></div></article>`).join(''):'<p class="empty">Aucun produit trouvé.</p>';document.querySelectorAll('[data-status]').forEach(s=>s.onchange=()=>{products=products.map(p=>p.id===s.dataset.status?{...p,status:s.value}:p);write(key,products);syncSelect();suggestion();render()});document.querySelectorAll('[data-fav2]').forEach(b=>b.onclick=()=>{products=products.map(p=>p.id===b.dataset.fav2?{...p,favorite:!p.favorite}:p);write(key,products);syncSelect();render()});suggestion()}
  ['brand-filter','model-filter','stock-filter','product-filter'].forEach(id=>$('#'+id)?.addEventListener('change',()=>{if(id==='brand-filter')fillModels();render()}));$('#product-search')?.addEventListener('input',render);
  const originalForm=$('#product-form');if(originalForm)originalForm.addEventListener('submit',()=>setTimeout(()=>{products=read(key,[]);const newest=products[products.length-1];if(newest&&$('#new-status')){newest.status=$('#new-status').value;write(key,products)}fillBrands();syncSelect();render()},0));
  fillBrands();syncSelect();render();
})();